# Generated by Django 4.2.7 on 2023-11-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='food_preference',
            field=models.CharField(blank=True, choices=[('omnivore', 'Omnivore'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
