# Generated by Django 4.2.7 on 2023-12-10 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_avg_rating_recipe_recipe_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_images',
            new_name='images',
        ),
    ]
