version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: "on-failure"
    depends_on:
      - postgres-db
    networks:
      - recipeApp

  postgres-db:
    image: postgres:12.1-alpine
    ports: 
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment: 
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=recipe
    restart: "on-failure"
    networks: 
      - recipeApp

networks:
  recipeApp:
    driver: bridge

volumes:
  postgres_data:
